from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from src.config import load_config
from src.agents.state import AgentState
from src.agents.nodes.orchestrator import orchestrator_node
from src.agents.nodes.scout import scout_node
from src.agents.nodes.reader import reader_node
from src.agents.nodes.critic import critic_node
from src.agents.nodes.synthesizer import synthesizer_node

# Load environment variables
load_config()

# Build the Graph
graph = StateGraph(AgentState)

# Add Nodes
graph.add_node("orchestrator", orchestrator_node)

def review_plan_node(state: AgentState) -> dict:
    # Dummy node to act as an interruption point. 
    # This prevents the graph from pausing when the Critic loops back directly to the scout.
    return {}

graph.add_node("review_plan", review_plan_node)
graph.add_node("scout", scout_node)
graph.add_node("reader", reader_node)
graph.add_node("critic", critic_node)
graph.add_node("synthesizer", synthesizer_node)

# Define Entry Point
graph.set_entry_point("orchestrator")

# Define edges
graph.add_edge("orchestrator", "review_plan")
graph.add_edge("review_plan", "scout")
graph.add_edge("scout", "reader")
graph.add_edge("reader", "critic")

def route_critic(state: AgentState) -> str:
    """
    If the Critic rejected a task, it removed it from 'completed_tasks'.
    If all tasks in the 'plan' are in 'completed_tasks', then everything 
    has passed the Critic's checks and we can synthesize. Otherwise, loop back.
    """
    plan = state.get("plan", [])
    completed_tasks = state.get("completed_tasks", [])
    
    # Check if we have a plan and all tasks have been completed and passed (id is in completed_tasks)
    if len(plan) > 0 and len(completed_tasks) == len(plan):
        return "synthesizer"
    
    # Otherwise, loop back to the scout to fetch the missing/failed data
    return "scout"

graph.add_conditional_edges(
    "critic",
    route_critic,
    {
        "synthesizer": "synthesizer",
        "scout": "scout"
    }
)

graph.add_edge("synthesizer", END)

# Compile the Graph
memory = MemorySaver()

# interrupt_before=["review_plan"] adds Human-In-The-Loop. 
# The graph execution will pause before the 'review_plan' node runs for the first time,
# allowing the user to review the state["plan"] generated by the Orchestrator.
# It does NOT pause when the Critic loops back to the Scout.
workflow = graph.compile(checkpointer=memory, interrupt_before=["review_plan"])